/**
 * agent-gateway — unified channel abstraction (nanobot-style).
 *
 * Channels (IM / web / ...) convert platform-specific messages into a generic
 * InboundMessage and hand them to the agent via a MessageBus; agent replies
 * travel back as OutboundMessage to the originating channel.
 */

import { randomUUID } from "node:crypto";
import type { OutboundEvent, StreamDeltaEvent, StreamEndEvent } from "./events.ts";

/** Stable identifier used to correlate a channel event across retries. */
export type MessageId = string;

/** Attachment kinds understood by the channel boundary. */
export type AttachmentKind = "file" | "image" | "audio" | "video";

/** Typed attachment reference used by inbound and outbound channel messages. */
export interface ChannelAttachment {
	kind: AttachmentKind;
	/** A URL, data URL, or path managed by the embedding application. */
	source: string;
	filename?: string;
	mimeType?: string;
	sizeBytes?: number;
	metadata?: Record<string, unknown>;
}

/** Optional context for a platform-native reply/quote. */
export interface ReplyReference {
	messageId: string;
	content?: string;
	senderId?: string;
	senderLabel?: string;
}

/** Image attachment normalized by a channel for multimodal agent input. */
export interface ImageAttachment {
	type: "image";
	/** Base64-encoded image data. */
	data: string;
	/** Image MIME type, e.g. image/jpeg or image/png. */
	mimeType: string;
}

/** Message received from a chat channel (channel -> agent). */
export interface InboundMessage {
	/** Stable platform/event id, generated when the platform does not provide one. */
	messageId: MessageId;
	/** Channel id, e.g. "web", "qq", "telegram". */
	channel: string;
	/** User identifier on the channel. */
	senderId: string;
	/** Chat/room identifier on the channel. */
	chatId: string;
	/** Message text. */
	content: string;
	/** Media references (URLs or local paths). */
	media?: string[];
	/** Typed media references for channel-agnostic consumers. */
	attachments?: ChannelAttachment[];
	/** Downloaded image attachments for multimodal agent input. */
	images?: ImageAttachment[];
	/** Platform thread identifier when the channel supports threads. */
	threadId?: string;
	/** Client-generated id used for idempotent handoff. */
	clientMessageId?: string;
	/** Native reply/quote context, when available. */
	replyTo?: ReplyReference;
	/** Channel-specific data (thread ids, message ids, ...). */
	metadata?: Record<string, unknown>;
	timestamp: number;
	/** Unique key for session identification. */
	readonly sessionKey: string;
	/** Explicit DM flag. When absent, channels infer it from chat type metadata. */
	isDm?: boolean;
	/**
	 * Authorization entity id: for group/room-scoped access this may differ
	 * from senderId (nanobot `authorization_id`). Permission checks use this
	 * when present; the sender's identity is preserved for session/routing.
	 */
	authorizationId?: string;
}

/** Message to send back to a chat channel (agent -> channel). */
export interface OutboundMessage {
	/** Stable logical message id. Generated by the SDK when omitted. */
	messageId?: MessageId;
	channel: string;
	chatId: string;
	content: string;
	/** Optional original message id this replies to. */
	replyTo?: string;
	/** Structured reply context for channels that can render a quote. */
	replyContext?: ReplyReference;
	/** Platform thread identifier (e.g. Slack thread_ts, Matrix thread root). */
	threadId?: string;
	media?: string[];
	attachments?: ChannelAttachment[];
	thinking?: string;
	/** Button rows; channels with interactive surfaces render them, others degrade to text. */
	buttons?: string[][];
	/** Typed outbound event (progress/stream end/turn end/...). Absent = plain text. */
	event?: OutboundEvent;
	/** Session-store id assigned to the assistant message, when available. */
	sessionMessageId?: string;
	/** Runtime turn id used by cancellation and lifecycle events. */
	turnId?: string;
	/** Channel routing context. */
	metadata?: Record<string, unknown>;
}

/** Streaming text chunk (optional channel support). */
export interface OutboundDelta {
	/** Stable logical stream event id. */
	messageId?: MessageId;
	channel: string;
	chatId: string;
	delta: string;
	/** Optional original message id this stream replies to (reply/quote). */
	replyTo?: string;
	/** Content kind: assistant answer text or model thinking. Default "text". */
	type?: "text" | "thinking";
	/** Opaque stream id; channels key their buffers on it when provided. */
	streamId?: string;
	/** True on the final chunk of a stream. */
	streamEnd?: boolean;
	/** True when this segment continues a previously interrupted stream. */
	resuming?: boolean;
	/** True when the next text segment belongs to the same user-visible message. */
	mergeNext?: boolean;
	/** Runtime turn id used by lifecycle events. */
	turnId?: string;
	/** Eventized delta: stream delta/end semantics. Absent = plain text delta. */
	event?: StreamDeltaEvent | StreamEndEvent;
}

/** Result returned by a platform adapter after a send attempt. */
export interface ChannelSendResult {
	status?: DeliveryStatus;
	providerMessageId?: string;
	canonicalMedia?: string[];
	detail?: string;
}

export type DeliveryStatus = "success" | "partial" | "failed" | "cancelled";

/** Structured result for a complete logical outbound message. */
export interface DeliveryReceipt {
	messageId: MessageId;
	channel: string;
	chatId: string;
	status: DeliveryStatus;
	attempts: number;
	acceptedAt: number;
	deliveredAt?: number;
	providerMessageId?: string;
	canonicalMedia?: string[];
	detail?: string;
}

/** Build a stable id for a message created inside the gateway. */
export function createMessageId(prefix = "msg"): MessageId {
	return `${prefix}_${randomUUID()}`;
}

/** Build the canonical session key: `${channel}:${chatId}`. */
export function buildSessionKey(channel: string, chatId: string): string {
	return `${channel}:${chatId}`;
}
